name: "Install Apprentice Licenses"
description: "Install Houdini Apprentice licenses for the duration of the tests."
inputs:
  client_id:
    description: "The SideFX Web API client_id value to use."
    required: true

  client_secret_key:
    description: "The SideFX Web API client_secret_key value to use."
    required: true

  houdini_version:
    description: "The houdini version to install for"
    default: "19.5"

runs:
  using: "composite"

  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash

    - uses: actions/setup-python@v4
      with:
        python-version: "pypy3.9"
    
    - name: Install dependencies
      run: python3 -m pip install requests

    - run: sesinetd
      shell: bash

    - run: python3 ${{ github.action_path }}/install_apprentice_keys.py ${{ inputs.client_id }} ${{ inputs.client_secret_key }} ${{ inputs.houdini_version }}
      shell: bash

    - run: hserver -h localhost:1715
      shell: bash

